### ISSUE TITLE
Allow server side rendering

### ISSUE THREAD

**Issue by cyberwombat** [souporserious/react-media-player#17]
Right now this yields a `ReferenceError: document is not defined`.

**Comment by souporserious** [comment]
Sorry about that! I'll get to it when I get a chance. PR's welcome :)

**Comment by cyberwombat** [comment]
I am working a bit on that. I think that the rendering of the elements themselves such as the video player are going to need to be conditional since they depend so much on document, script tags for remote APIs etc. What I am tying to get at is to import the modules without errors then conditionally render them if browser.

**Comment by cyberwombat** [comment]
I see 2 things so far. One is pretty easy - the exit/enter fullscreen need to not autoinvoke but instead be invoked in the Media component as ` document[exitFullscreen()]()`. That takes care of the document error on SSR. The other I am not sure how to handle - the AudioPlayer instantiates the AudioContext outside of the component. I guess moving that bit and the panner code inside the component is the approach however I can't tell if this component is a work in progress. I have the panner bar show under the component and it creates various errors on its own so perhaps you can take a looksy at that part.

**Comment by souporserious** [comment]
Hmm interesting. What kind of errors does the panner produce? I'm wondering if it would be bad to just not render anything until the document is available? Or would that hurt SEO somehow? Sorry, I'm not too familiar with SSR yet :/

**Comment by cyberwombat** [comment]
I'll get back to you on the errors - refactoring some code before I get back to the panner. As far as the SSR. I don't think it s truly possible to do full SSR in all cases because it may load a remote API like Vimeo but at the very least we should be able to import the media player components and render them if in browser. As in stands right now because of the Fullscreen/AudioContext setup it does not allow ES6 imports on server since the document/window does not exist. Refactoring a bit allows imports then it's easy to do something like:

    { isBrowser ? <AudioPlayer/> : null } 

Hope that makes sense.

**Comment by meteorplus** [comment]
const isBrowser = typeof window !== 'undefined';
const { Media, Player, controls } = isBrowser ? require('react-media-player') : {}
const { PlayPause, MuteUnmute, } = isBrowser ? controls : {}

and works fine

**Comment by rwieruch** [comment]
@meteorplus did you manage to use `withMediaProps` as well?

**Comment by romanenko** [comment]
This should be fixed with PR #40. We should, probably, close this issue.

**Comment by souporserious** [comment]
@KyleAMathews thanks for the info! Looks like I need to add a check for `Audio` availability. I'll get to this when I get a chance @jserrao, please feel free to add a PR if you'd like.

**Comment by jserrao** [comment]
@souporserious - I'll take a look. By the way, really nice little package - everything works great.

I rearranged some of the code you provided for an audio player inside of a `componentDidMount()` lifecycle method, which helped part of the problem in my custom component. The whole still throws an error, looking for `Audio` deeper in the dependency chain. I haven't had a chance to dive in on this, but I probably will tomorrow.

For reference here is the component I put together, heavily based on your example. This work in both Gatsby and I tested it in a `next.js` app I've got - so only really minor changes were needed on that side of the fence:

```
import React, { Component } from 'react'
import { Media, Player, controls } from 'react-media-player'
import PlayPause from './PlayPause'
import MuteUnmute from './MuteUnmute'

const { CurrentTime, SeekBar, Duration, Volume } = controls
let panner = null

class AudioPlayer extends Component {
  componentDidMount() {
    const audioContext = new (window.AudioContext || window.webkitAudioContext)()
    panner = audioContext.createPanner()
    
    panner.setPosition(0, 0, 1)
    panner.panningModel = 'equalpower'
    panner.connect(audioContext.destination)

    const source = audioContext.createMediaElementSource(this._player.instance)
    source.connect(panner)
    panner.connect(audioContext.destination)
  }

  _handlePannerChange = ({ target }) => {
    const x = +target.value
    const y = 0
    const z = 1 - Math.abs(x)
    panner.setPosition(x, y, z)
  }

  render() {
    return (
      <Media>
        <div>
          <Player
            ref={c => this._player = c}
            src={this.props.src}
            useAudioObject
          />
          <section className="media-controls">
            <div className="media-title-box">
              <PlayPause className="media-control media-control--play-pause"/>
              <div className="media-title-content">
                <div className="media-title">{ this.props.mediaTitle }</div>
                <div className="media-subtitle">{ this.props.mediaSubtitle }</div>
              </div>
            </div>
            <div className="media-controls-container">
              <CurrentTime className="media-control media-control--current-time"/>
              <SeekBar className="media-control media-control--volume-range"/>
              <Duration className="media-control media-control--duration"/>
            </div>
            <div className="media-sound-controls">
              <MuteUnmute className="media-control media-control--mute-unmute"/>
              <Volume className="media-control media-control--volume"/>
            </div>            
          </section>
        </div>
      </Media>
    )
  }
}

export default AudioPlayer
```

**Comment by souporserious** [comment]
Fixed in https://github.com/souporserious/react-media-player/pull/53
